// priority: 10
const Color = [
	'brown',
	'white',
	'orange',
	'magenta',
	'light_blue',
	'yellow',
	'lime',
	'pink',
	'gray',
	'light_gray',
	'cyan',
	'purple',
	'blue',
	'green',
	'red',
	'black',
]
ServerEvents.recipes(event => {
    // === remove mod ================================================================================
    event.remove({input: ['#create:crushed_raw_materials'], type: 'create:splashing'})
    event.remove({output: ['#create:crushed_raw_materials'], type: 'create:crushing'})
	 //event.remove({type: 'tfmg:casting'})

	// ====replace item on crafting ==================================================================
	event.replaceInput({type: 'minecraft:crafting_shaped'}, 'create:zinc_ingot', '#forge:ingots/zinc')
	event.replaceInput({mod: 'copycats'}, '#forge:ingots/zinc', '#forge:sheets/zinc')
    event.replaceInput({mod: 'create'}, 'supplementaries:flax', '#forge:crops/flax')
	event.replaceInput({mod: 'createaddition'}, 'createaddition:capacitor', '#forge:electronics/capacitor')
    event.replaceInput({mod: 'tfmg'}, 'tfmg:copper_cable', 'immersiveengineering:wirecoil_copper')
	
	// ====remove  id recipe =========================================================================
    event.remove([
		//{id: 'create:deploying/cogwheel'},
		//{id: 'create:deploying/large_cogwheel'},
		{id: 'create:andesite_alloy'},
		{id: 'create:blasting/ingot_nickel_compat_immersiveengineering'},
		{id: 'create:blasting/ingot_silver_compat_immersiveengineering'},
		{id: 'create:blasting/zinc_ingot_from_crushed'},
		{id: 'create:crafting/appliances/book'},
		{id: 'create:crafting/appliances/dough'},
		{id: 'create:crafting/appliances/name_tag'},
		{id: 'create:crafting/kinetics/fluid_pipe_vertical'},
		{id: 'create:crafting/kinetics/encased_chain_drive_from_zinc'},
		{id: 'create:crafting/materials/brass_ingot_from_compacting'},
		{id: 'create:crafting/materials/brass_ingot_from_decompacting'},
		{id: 'create:crafting/tree_fertilizer'},
		{id: 'create:crushing/asurine_recycling'},
		{id: 'create:crushing/asurine'},
		{id: 'create:crushing/blaze_rod'},
		{id: 'create:crushing/crimsite_recycling'},
		{id: 'create:crushing/crimsite'},
		{id: 'create:crushing/diamond_horse_armor'},
		{id: 'create:crushing/diorite_recycling'},
		{id: 'create:crushing/diorite'},
		{id: 'create:crushing/golden_horse_armor'},
		{id: 'create:crushing/gravel'},
		{id: 'create:crushing/iron_horse_armor'},
		{id: 'create:crushing/leather_horse_armor'},
		{id: 'create:crushing/ochrum_recycling'},
		{id: 'create:crushing/ochrum'},
		{id: 'create:crushing/tuff_recycling'},
		{id: 'create:crushing/tuff'},
		{id: 'create:crushing/veridium_recycling'},
		{id: 'create:crushing/veridium'},

		{id: 'create:crafting/kinetics/sail_frame_from_conversion'},
		{id: 'create:crafting/kinetics/white_sail_from_conversion'},

		{id: 'create:deploying/copper_block_from_deoxidising'},
		{id: 'create:deploying/exposed_copper_from_deoxidising'},
		{id: 'create:deploying/weathered_copper_from_deoxidising'},
		{id: 'create:deploying/copper_block_from_removing_wax'},
		{id: 'create:deploying/exposed_copper_from_removing_wax'},
		{id: 'create:deploying/wweathered_copper_from_removing_wax'},
		
		{id: 'create:milling/cobblestone'},
		{id: 'create:milling/gravel'},
		{id: 'create:milling/saddle'},
		{id: 'create:milling/sugar_cane'},
		{id: 'create:milling/wheat'},

		{id: 'create:mixing/chocolate_melting'},
		{id: 'create:mixing/lava_from_cobble'},		
		
		{id: 'create:pressing/brass_ingot'},
		{id: 'create:pressing/copper_ingot'},
		{id: 'create:pressing/desh_ingot'},
		{id: 'create:pressing/calorite_ingot'},
		{id: 'create:pressing/ostrum_ingot'},
		{id: 'create:pressing/gold_ingot'},
		{id: 'create:pressing/iron_ingot'},
		{id: 'create:pressing/sugar_cane'},
		{id: 'create:pressing/compat/immersiveengineering/plate_constantan'},
		{id: 'create:pressing/compat/immersiveengineering/plate_electrum'},
		{id: 'create:pressing/compat/immersiveengineering/plate_lead'},
		{id: 'create:pressing/compat/immersiveengineering/plate_uranium'},

		{id: 'create:smelting/ingot_nickel_compat_immersiveengineering'},
		{id: 'create:smelting/ingot_silver_compat_immersiveengineering'},
		{id: 'create:smelting/zinc_ingot_from_crushed'},
		
		{id: 'create:splashing/mekanism/crushed_raw_lead'},
		{id: 'create:splashing/mekanism/crushed_raw_uranium'},
		{id: 'create:splashing/wheat_flour'},
		{id: 'create:splashing/sand'},
		//
		{id: 'create_sa:magma_cream_recipe'},
		//{id: 'create_sa:brass_cube_uncrafting'},
		//
		{id: 'createaddition:anvil/electrum'},
		{id: 'createaddition:compat/immersiveengineering/constantan'},
		{id: 'createaddition:compat/immersiveengineering/crushing/steel_ingot'},
		{id: 'createaddition:compat/immersiveengineering/crushing/coke_block'},
		{id: 'createaddition:compat/immersiveengineering/crushing/coal_coke'},
		{id: 'createaddition:compat/immersiveengineering/electrum'},
		{id: 'createaddition:compat/immersiveengineering/fabric_sail'},
		{id: 'createaddition:compat/immersiveengineering/item_application/kiln_brick'},
		{id: 'createaddition:compat/immersiveengineering/item_application/reinforced_blast_brick'},
		{id: 'createaddition:compat/tconstruct/hepatizon'},
		{id: 'createaddition:compat/tconstruct/manyullyn'},
		{id: 'createaddition:compat/tconstruct/queens_slime'},
		{id: 'createaddition:compat/tconstruct/rose_gold'},
		{id: 'createaddition:compat/tconstruct/slimesteel'},
		{id: 'createaddition:crafting/electrum_ingot'},
		{id: 'createaddition:mixing/electrum'},
		{id: 'createaddition:mixing/bioethanol'},
		{id: 'createaddition:pressing/aluminum_ingot'},
		{id: 'createaddition:pressing/brass_ingot'},
		{id: 'createaddition:pressing/constantan_ingot'},
		{id: 'createaddition:pressing/electrum_ingot'},
		{id: 'createaddition:pressing/electrum_plate'},
		{id: 'createaddition:pressing/lead_ingot'},
		{id: 'createaddition:pressing/uranium_ingot'},
		{id: 'createaddition:pressing/zinc_ingot'},
		{id: 'createaddition:rolling/aluminum_plate'},
		{id: 'createaddition:rolling/electrum_ingot'},
		{id: 'createaddition:rolling/lead_plate'},
		{id: 'createaddition:rolling/steel_plate'},
		//
		{id: 'create_mechanical_extruder:extruding/limestone'},
		{id: 'create_mechanical_extruder:extruding/scoria'},
		//
		{id: 'createdieselgenerators:basin_fermenting/dough'},
		{id: 'createdieselgenerators:basin_fermenting/golden_carrot'},
		{id: 'createdieselgenerators:basin_fermenting/golden_apple'},
		{id: 'createdieselgenerators:bulk_fermenting/fermentable'},
		{id: 'createdieselgenerators:bulk_fermenting/magma_cream'},
		{id: 'createdieselgenerators:bulk_fermenting/lava'},
		{id: 'createdieselgenerators:casting/chocolate_bar'},
		{id: 'createdieselgenerators:compacting/plant_oil'},
		{id: 'createdieselgenerators:compat/createaddition/copper_rod'},
		{id: 'createdieselgenerators:compat/createaddition/copper_wire'},
		{id: 'createdieselgenerators:compat/createaddition/electrum_rod'},
		{id: 'createdieselgenerators:compat/createaddition/electrum_sheet'},
		{id: 'createdieselgenerators:compat/createaddition/electrum_wire'},
		{id: 'createdieselgenerators:compat/createaddition/gold_rod'},
		{id: 'createdieselgenerators:compat/createaddition/gold_wire'},
		{id: 'createdieselgenerators:compat/createaddition/iron_rod'},
		{id: 'createdieselgenerators:compat/createaddition/iron_wire'},
		{id: 'createdieselgenerators:compat/createaddition/zinc_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/aluminum_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/constantan_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/copper_wire'},
		{id: 'createdieselgenerators:compat/immersiveengineering/electrum_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/electrum_wire'},
		{id: 'createdieselgenerators:compat/immersiveengineering/graphite_electrode'},
		{id: 'createdieselgenerators:compat/immersiveengineering/herbicide'},
		{id: 'createdieselgenerators:compat/immersiveengineering/nickel_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/silver_sheet'},
		{id: 'createdieselgenerators:compat/immersiveengineering/steel_wire'},
		{id: 'createdieselgenerators:compat/immersiveengineering/uranium_sheet'},
		{id: 'createdieselgenerators:compression_molding/blaze_rod'},
		{id: 'createdieselgenerators:compression_molding/bowl'},
		{id: 'createdieselgenerators:compression_molding/bucket'},
		//{id: 'createdieselgenerators:compression_molding/chain'},
		{id: 'createdieselgenerators:compression_molding/stick'},

		{id: 'createdieselgenerators:distillation/superheated_crude_oil'},
		{id: 'createdieselgenerators:hammering/brass_sheet'},
		{id: 'createdieselgenerators:hammering/copper_sheet'},
		{id: 'createdieselgenerators:hammering/gold_sheet'},
		{id: 'createdieselgenerators:hammering/iron_sheet'},

		{id: 'createdieselgenerators:crafting/asphalt_block'},
		{id: 'createdieselgenerators:crafting/asphalt_stairs'},
		{id: 'createdieselgenerators:crafting/asphalt_slab'},
		{id: 'createdieselgenerators:mixing/asphalt_block'},
		{id: 'createdieselgenerators:mixing/biodiesel'},
		//
		{id: 'create_hc:gear_small'},
		{id: 'create_hc:gear_large'},
		//
		{id: 'createbigcannons:gunpowder_pinch'},
		{id: 'createbigcannons:gunpowder_from_pinches'},
		{id: 'createbigcannons:melting/melt_bronze_block'},
		{id: 'createbigcannons:melting/melt_bronze_ingot'},
		{id: 'createbigcannons:melting/melt_bronze_nugget'},
		{id: 'createbigcannons:melting/melt_cast_iron_ingot'},
		{id: 'createbigcannons:melting/melt_cast_iron_block'},
		{id: 'createbigcannons:melting/melt_cast_iron_nugget'},
		{id: 'createbigcannons:melting/melt_steel_block'},
		{id: 'createbigcannons:melting/melt_steel_nugget'},
		{id: 'createbigcannons:melting/melt_steel_ingot'},
		{id: 'createbigcannons:mixing/alloy_nethersteel_cast_iron'},
		{id: 'createbigcannons:mixing/alloy_nethersteel_steel'},
		{id: 'createbigcannons:alloy/nethersteel_cast_iron'},
		{id: 'createbigcannons:alloy/nethersteel_steel'},
		{id: 'createbigcannons:compacting/forge_nethersteel_nugget'},
		{id: 'createbigcannons:compacting/forge_nethersteel_ingot'},
		//
		{id: `/^createlowheated:mixing/.*/`},
		//
		{id: 'create_sa:quartz_gem_crushing'},
		//
		{id: 'createsifter:sifting/dirt_strig_mesh_waterlogged'},
		{id: 'createsifter:sifting/gravel_advanced_brass_mesh'},
		{id: 'createsifter:sifting/gravel_andesite_mesh'},
		{id: 'createsifter:sifting/gravel_brass_mesh'},
		{id: 'createsifter:sifting/gravel_zinc_mesh'},
		{id: 'createsifter:sifting/sand_andesite_mesh'},
		{id: 'createsifter:sifting/sand_brass_mesh'},
		{id: 'createsifter:sifting/sand_string_mesh'},
		{id: 'createsifter:sifting/sand_zinc_mesh'},
		{id: 'createsifter:sifting/soul_sand_brass_mesh'},
		{id: 'createsifter:sifting/soul_sand_advanced_brass_mesh'},
		//
		{id: 'createmetallurgy:alloying/steel'},
		{id: 'createmetallurgy:sequenced_assembly/steel_track'},
		{id: 'createmetallurgy:blasting/coke_from_coal'},
		{id: 'createmetallurgy:casting_in_basin/andesite_alloy_from_iron'},
		{id: 'createmetallurgy:casting_in_basin/andesite_alloy_from_zinc'},
		{id: 'createmetallurgy:casting_in_table/aluminum/plate'},
		{id: 'createmetallurgy:casting_in_table/aluminum/rod'},
		{id: 'createmetallurgy:casting_in_table/brass/plate'},
		{id: 'createmetallurgy:casting_in_table/brass/rod'},
		{id: 'createmetallurgy:casting_in_table/bronze/plate'},
		{id: 'createmetallurgy:casting_in_table/bronze/rod'},
		{id: 'createmetallurgy:casting_in_table/constantan/plate'},
		{id: 'createmetallurgy:casting_in_table/constantan/rod'},
		{id: 'createmetallurgy:casting_in_table/copper/plate'},
		{id: 'createmetallurgy:casting_in_table/copper/rod'},
		{id: 'createmetallurgy:casting_in_table/electrum/plate'},
		{id: 'createmetallurgy:casting_in_table/electrum/rod'},
		{id: 'createmetallurgy:casting_in_table/gold/plate'},
		{id: 'createmetallurgy:casting_in_table/gold/rod'},
		{id: 'createmetallurgy:casting_in_table/invar/plate'},
		{id: 'createmetallurgy:casting_in_table/invar/rod'},
		{id: 'createmetallurgy:casting_in_table/iron/plate'},
		{id: 'createmetallurgy:casting_in_table/iron/rod'},
		{id: 'createmetallurgy:casting_in_table/lead/plate'},
		{id: 'createmetallurgy:casting_in_table/lead/rod'},
		{id: 'createmetallurgy:casting_in_table/netherite/plate'},
		{id: 'createmetallurgy:casting_in_table/netherite/rod'},
		{id: 'createmetallurgy:casting_in_table/nickel/plate'},
		{id: 'createmetallurgy:casting_in_table/nickel/rod'},
		{id: 'createmetallurgy:casting_in_table/osmium/plate'},
		{id: 'createmetallurgy:casting_in_table/osmium/rod'},
		{id: 'createmetallurgy:casting_in_table/silver/plate'},
		{id: 'createmetallurgy:casting_in_table/silver/rod'},
		{id: 'createmetallurgy:casting_in_table/steel/plate'},
		{id: 'createmetallurgy:casting_in_table/steel/rod'},
		{id: 'createmetallurgy:casting_in_table/tin/plate'},
		{id: 'createmetallurgy:casting_in_table/tin/rod'},
		{id: 'createmetallurgy:casting_in_table/tungsten/plate'},
		{id: 'createmetallurgy:casting_in_table/tungsten/rod'},
		{id: 'createmetallurgy:casting_in_table/zinc/plate'},
		{id: 'createmetallurgy:casting_in_table/zinc/rod'},
		{id: 'createmetallurgy:compat/immersiveenginnering/graphite_electrode'},
		{id: 'createmetallurgy:crafting/materials/graphite'},
		
		{id: 'createmetallurgy:pressing/graphite'},
		//{id: 'create:crafting/kinetics/large_cogwheel_from_little'},
		//{id: 'create:crafting/kinetics/gearboxfrom_conversion'},
		//
		{id: 'vintageimprovements:osmium_ingot'},
		{id: 'vintageimprovements:curving/iron_sheet'},
		{id: 'vintageimprovements:rolling/aluminum_plate'},		
		{id: 'vintageimprovements:rolling/brass_plate'},		
		{id: 'vintageimprovements:rolling/bronze_plate'},		
		{id: 'vintageimprovements:rolling/cast_iron_plate'},		
		{id: 'vintageimprovements:rolling/constantan_plate'},		
		{id: 'vintageimprovements:rolling/lead_plate'},		
		{id: 'vintageimprovements:rolling/nickel_plate'},		
		{id: 'vintageimprovements:rolling/rose_gold_plate'},		
		{id: 'vintageimprovements:rolling/tin_plate'},		
		{id: 'vintageimprovements:rolling/zinc_plate'},		
		{id: 'vintageimprovements:rolling/osmium_ingot'},		
		{id: 'vintageimprovements:rolling/cobalt_ingot'},		
		{id: 'vintageimprovements:rolling/electrum_wire'},		
		{id: 'vintageimprovements:pressing/silver_plate'},		
		{id: 'vintageimprovements:pressing/steel_plate'},		
		{id: 'vintageimprovements:pressing/uranium_ingot'},
		{id: 'vintageimprovements:pressing/osmium_ingot'},
		{id: 'vintageimprovements:pressing/cobalt_ingot'},
		{id: 'vintageimprovements:pressing/rose_gold_ingot'},
		{id: 'vintageimprovements:pressing/silver_ingot'},
		{id: 'vintageimprovements:pressing/vanadium_ingot'},
		{id: 'vintageimprovements:pressing/constantan_ingot'},
		{id: 'vintageimprovements:pressing/platinum_ingot'},

		{id: 'tfmg:crushing/coal_coke'},
		{id: 'tfmg:distillation/crude_oil_no_naphtha'},
		{id: 'tfmg:distillation/heavy_oil_no_naphtha'},
		{id: 'tfmg:distillation/crude_oil_light_distillation'},
		{id: 'tfmg:distillation/heavy_oil_light_distillation'},
		{id: 'tfmg:mixing/napalm'},
		{id: 'tfmg:crafting/kinetics/napalm_bomb'},
		{id: 'tfmg:crafting/kinetics/plastic_pipe'},
		{id: 'tfmg:compacting/bitumen'},
		{id: 'tfmg:vat_machine_recipe/suluric_acid'},
		{id: 'tfmg:pressing/aluminum_ingot'},
		{id: 'tfmg:pressing/cast_iron_ingot'},
		{id: 'tfmg:pressing/lead_ingot'},
		{id: 'tfmg:pressing/nickel_ingot'},	
		{id: 'tfmg:industrial_blasting/steel'},
		{id: 'tfmg:industrial_blasting/steel_from_raw_iron'},
		{id: 'tfmg:industrial_blasting/steel_from_dust'},
		{id: 'tfmg:graphite_electrode_from_coal_coke_block_stonecutting'}
	])
	Color.forEach((colors) => {
		event.remove([
			{id: `createmetallurgy:crafting/${colors}_light_bulb`},
		])
	})
    // ==== remove all ===================================================
    event.remove({output: [
		//'create_hc:saw_blade',
		//'create_hc:drill_head',
		`/^create:.*_toolbox/`,
		'create:bar_of_chocolate',
		'create:brass_ingot',
		'create:brass_sheet',
		'create:copper_sheet',
		'create:golden_sheet',
		'create:iron_sheet',
		'create:red_sand_paper',
		'create:zinc_ingot',
		'create:zinc_sheet',
		//
		'createbigcannons:cast_iron_ingot',
		'createbigcannons:cast_iron_nugget',
		'createbigcannons:cast_iron_block',
		'createbigcannons:spring_wire',
		'createbigcannons:basin_foundry_lid',
		//
		'create_hc:press_head',
		'create_hc:rope',
		'create_hc:shaft',
		//
		//'create_new_age:nuclear_fuel',
		//'create_new_age:radioactive_thorium',
		//'create_new_age:reactor_casing',
		//'create_new_age:reactor_fuel_acceptor',
		//'create_new_age:reactor_glass',
		//'create_new_age:reactor_heat_acceptor',
		//'create_new_age:reactor_heat_vent',
		//'create_new_age:reactor_rod',
		//'create_new_age:thorium',
		//
		'createdieselgenerators:wood_chip',
		//
		'create_sa:block_picker',
		'create_sa:brass_axe',
		'create_sa:brass_hoe',
		'create_sa:brass_pickaxe',
		'create_sa:brass_shovel',
		'create_sa:brass_sword',
		'create_sa:copper_axe',
		'create_sa:copper_boots',
		'create_sa:copper_chestplate',
		'create_sa:copper_helmet',
		'create_sa:copper_hoe',
		'create_sa:copper_leggings',
		'create_sa:copper_magnet',
		'create_sa:copper_pickaxe',
		'create_sa:copper_shovel',
		'create_sa:copper_sword',
		'create_sa:slime_helmet',
		'create_sa:slime_boots',
		'create_sa:zinc_axe',
		'create_sa:zinc_hoe',
		'create_sa:zinc_pickaxe',
		'create_sa:zinc_shovel',
		'create_sa:zinc_sword',
		//
		'createaddition:electrum_ingot',
		'createaddition:electrum_block',
		//
		'createmetallurgy:crushed_raw_wolframite',
		'createmetallurgy:raw_wolframite',
		'createmetallurgy:dirty_wolframite_dust',
		'createmetallurgy:wolframite_dust',
		'createmetallurgy:wolframite_ore',
		'createmetallurgy:raw_wolframite_block',
		'createmetallurgy:tungsten_block',
		'createmetallurgy:tungsten_ingot',
		'createmetallurgy:tungsten_sheet',
		'createmetallurgy:tungsten_nugget',
		'createmetallurgy:tungsten_wire',
		//
		'createnergy:silver_block',
		'createnergy:silver_ingot',
		//
		'createsifter:andesite_mesh',
		'createsifter:zinc_mesh',
		//
		//'tfmg:block_mold',
		//'tfmg:ingot_mold',
		//'tfmg:casting_spout',
		'tfmg:asphalt',
		'tfmg:steel_block',
		'tfmg:aluminum_block',
		'tfmg:lead_copper',
		'tfmg:nickel_block',
		'tfmg:coal_coke_block',
		'tfmg:lead_ore',
		'tfmg:deepslate_lead_ore',
		'tfmg:deepslate_nickel_ore',
		'tfmg:nickel_ingot',
		'tfmg:nickel_ore',
		'tfmg:lithium_ore',
		'tfmg:deepslate_lithium_ore',
		'tfmg:sulfur',
		'tfmg:lignite',
		'tfmg:aluminum_ingot',
		'tfmg:cast_iron_ingot',
		'tfmg:lead_ingot',
		'tfmg:coal_coke',
		'tfmg:heavy_plate',
		'tfmg:steel_ingot',
		'tfmg:lead_ingot',
		'tfmg:copper_wire',
		'tfmg:aluminum_wire',
		'tfmg:raw_lead',
		'tfmg:raw_nickel',
		'tfmg:steel_helmet',
		'tfmg:steel_chestplate',
		'tfmg:steel_leggings',
		'tfmg:steel_boots',
		'tfmg:copper_cable',
		'tfmg:steel_axe',
		'tfmg:steel_hoe',
		'tfmg:steel_shovel',
		'tfmg:steel_pickaxe',
		'tfmg:steel_sword',
		'tfmg:aluminum_axe',
		'tfmg:aluminum_hoe',
		'tfmg:aluminum_shovel',
		'tfmg:aluminum_pickaxe',
		'tfmg:aluminum_sword',
		'tfmg:lead_axe',
		'tfmg:lead_hoe',
		'tfmg:lead_shovel',
		'tfmg:lead_pickaxe',
		'tfmg:lead_sword',
		'tfmg:sulfur_dust',
		'tfmg:sulfur_dust',
		'tfmg:copper_coil',
		'tfmg:constantan_ingot',
		'tfmg:constantan_block',
		'tfmg:constantan_nugget',
		'tfmg:constantan_wire'
	]})
})