// priority: 10
const DeleteOutputItems = [
	'create:adjustable_chain_gearshift',
	'create:analog_lever',
	'create:andesite_door',
	'create:attribute_filter',
	'create:basin',
	'create:belt_connector',
	'create:crafter_slot_cover',
	'create:elevator_pulley',
	'create:empty_blaze_burner',
	'create:encased_chain_drive',
	'create:encased_fan',
	'create:filter',
	'create:fluid_pipe',
	'create:fluid_pipe_vertical',
	'create:fluid_tank',
	'create:hose_pulley',
	'create:item_drain',
	'create:item_vault',
	'create:mechanical_press',
	'create:metal_bracket',
	'create:millstone',
	'create:spout',
	'create:steam_whistle',
	'create:sticker',
	'create:windmill_bearing',
	'create:wrench',
	'create:andesite_funnel',
	'create:andesite_tunnel',
	'create:brass_funnel',
	'create:brass_tunnel',
	'create:redsont_contact',
	'create:rose_quartz',
	'create:sand_paper',
	'create:crushing_wheel',
	'create:extendo_grip',
	'create:potato_cannon',
	'create:wand_of_symmetry',
	'create:empty_schematic',
	'create:schematiccannon',
	'create:schematic_and_quill',
	'create:schematic_table',
	'create:precision_mechanism',
	'create:strudy_sheet',
	'minecraft:bone_meal',
	'tfc:powder/charcoal',	
	'#tfc:foods/flour',
	'#tfc:foods/cooked_meats',
]
ServerEvents.recipes(event => {
    // === remove mod =====================================================
	event.remove({input: ['#tfc:foods/breads'], type: 'minecraft:smoking'})
	event.remove({input: ['#tfc:ore_pieces'], mod: 'woodencog'})
	event.remove({input: ['#tfc:small_ore_pieces'], mod: 'woodencog'})
	event.remove({output: ['#tfc:unfired_molds'], type: 'create:compacting'})
	event.remove({output: ['#tfc:stone_tools'], type: 'create:cutting'})
	event.remove({output: [ DeleteOutputItems ], mod: 'woodencog'})

	event.remove({output: ['#forge:dyes'], mod: 'woodencog'})

	// ====replace item on crafting =======================================
	//event.replaceInput({type: 'minecraft:crafting_shaped'}, 'create:zinc_ingot', '#forge:ingots/zinc')
    // ====remove  id recipe ==============================================
    event.remove([
		//{id: /woodencog:mixing\/ingot_to_liquid_*/},
		//{id: /woodencog:mixing\/create_mixing_alloying_*/},
		{id: /woodencog:heated_compacting\/*/},
		{id: /woodencog:heated_pressing\/*/},
		{id: /woodencog:heated_mixing\/*/},
		//
		{id: 'woodencog:compacting/brick'},
        {id: 'woodencog:compacting/bowl_2'},
        {id: 'woodencog:compacting/bowl_4'},
        {id: 'woodencog:compacting/crucible'},
        {id: 'woodencog:compacting/flower_pot'},
        {id: 'woodencog:compacting/spindle_head'},
        {id: 'woodencog:compacting/pan'},
        {id: 'woodencog:compacting/pot'},
        {id: 'woodencog:compacting/jug'},
        {id: 'woodencog:compacting/vessel'},
        {id: 'woodencog:compacting/large_vessel'},
        {id: 'woodencog:compacting/blowpipe'},
		//
		{id: 'woodencog:crafting/appliances/copper_backtank'},
		{id: 'woodencog:crafting/appliances/copper_diving_boots'},
		{id: 'woodencog:crafting/appliances/copper_diving_helmet'},
		{id: 'woodencog:crafting/appliances/crafting_blueprint'},
		{id: 'woodencog:crafting/appliances/linked_controller'},
		{id: 'woodencog:crafting/item_application/copper_casing_from_log'},
		{id: 'woodencog:crafting/item_application/copper_casing_from_wood'},
		{id: 'woodencog:crafting/item_application/railway_casing'},
		{id: 'woodencog:crafting/sequenced_assembly/sturdy_sheet'},
		{id: 'woodencog:crafting/sequenced_assembly/track'},
		{id: 'woodencog:crafting/logistics/redstone_contact'},
		//
		{id: 'woodencog:crushing/crushing_olive'},
		{id: 'woodencog:crushing/milling_olive'},
		//
		{id: 'woodencog:cutting/boots'},
		{id: 'woodencog:cutting/chestplate'},
		{id: 'woodencog:cutting/helmet'},
		{id: 'woodencog:cutting/horse_armor'},
		{id: 'woodencog:cutting/leggings'},
		{id: 'woodencog:cutting/saddle'},
		//
        {id: 'woodencog:heating/barley_dough.json'},
        {id: 'woodencog:heating/maize_dough.json'},
        {id: 'woodencog:heating/oat_dough.json'},
        {id: 'woodencog:heating/rice_dough.json'},
        {id: 'woodencog:heating/rye_dough.json'},
        {id: 'woodencog:heating/wheat_dough.json'},
        {id: 'woodencog:heating/seaweed.json'},
        {id: 'woodencog:heating/torch_from_stick_bunch.json'},
		//
        {id: 'woodencog:mixing/barrel/sugar'},
        {id: 'woodencog:mixing/barrel/mortar'},
        {id: 'woodencog:mixing/barrel/small_leather'},
        {id: 'woodencog:mixing/barrel/medium_leather'},
        {id: 'woodencog:mixing/barrel/large_leather'},
		{id: 'woodencog:mixing/barrel/small_soaked_hide'},
        {id: 'woodencog:mixing/barrel/medium_soaked_hide'},
        {id: 'woodencog:mixing/barrel/large_soaked_hide'},
		{id: 'woodencog:mixing/barrel/small_prepared_hide'},
        {id: 'woodencog:mixing/barrel/medium_prepared_hide'},
        {id: 'woodencog:mixing/barrel/large_prepared_hide'},
        {id: 'woodencog:mixing/barrel/beer'},
        {id: 'woodencog:mixing/barrel/cider'},
        {id: 'woodencog:mixing/barrel/rum'},
        {id: 'woodencog:mixing/barrel/sake'},
        {id: 'woodencog:mixing/barrel/vodka'},
        {id: 'woodencog:mixing/barrel/whiskey'},
        {id: 'woodencog:mixing/barrel/corn_whiskey'},
        {id: 'woodencog:mixing/barrel/rye_whiskey'},
        {id: 'woodencog:mixing/barrel/clean_jute_net'},
        {id: 'woodencog:mixing/barrel/curdling'},
        {id: 'woodencog:mixing/barrel/candle'},
        {id: 'woodencog:mixing/barrel/jute_fiber'},
        {id: 'woodencog:mixing/barrel/vinegar'},
        {id: 'woodencog:mixing/barrel/tannin'},
		//
		{id: 'woodencog:rock_knapping/andesite_alloy'},
		{id: 'woodencog:rock_knapping/andesite_alloy_deploying'},		
    ])
})