// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

StartupEvents.registry("fluid", (event) => {
	event.create("diamond")						.thickTexture(0x33ffff).bucketColor(0x33ffff)	.displayName("Molten Diamond").noBlock() 
	event.create("diamond_steel")				.thickTexture(0x339999).bucketColor(0x339999)	.displayName("Molten Diamond Steel").noBlock() 
	event.create("netherite")					.thickTexture(0x333333).bucketColor(0x333333)	.displayName("Molten Netherite").noBlock() 
	event.create("ender")						.thickTexture(0x339966).bucketColor(0x339966)	.displayName("Molten Ender").noBlock() 
	event.create("iron_quartz")					.thickTexture(0xdedede).bucketColor(0xdedede)	.displayName("Molten Quartz Enriched Iron").noBlock() 
	event.create("quartz")						.thickTexture(0xcccccc).bucketColor(0xcccccc)	.displayName("Molten Quartz").noBlock() 
	event.create("glass")						.thickTexture(0xccecff).bucketColor(0xccecff)	.displayName("Molten Glass").noBlock() 
	event.create("andesite_alloy")				.thickTexture(0x669999).bucketColor(0x669999)	.displayName("Molten Andesite Alloy").noBlock()
	event.create("andesite_stone")				.thickTexture(0x666666).bucketColor(0x666666)	.displayName("Molten Andesite Stone").noBlock()
	event.create("purified_water")				.thinTexture(0x003366).bucketColor(0x003366)	.displayName("Purified Water").noBlock()
	event.create("boiled_water")				.thinTexture(0x6699cc).bucketColor(0x6699cc)	.displayName("Boiled Water").noBlock()
	event.create("herbal_water")				.thinTexture(0x336666).bucketColor(0x336666)	.displayName("Herbal Water").noBlock()
	event.create("mineral_water")				.thinTexture(0x3399ff).bucketColor(0x3399ff)	.displayName("Mineral Water").noBlock()
	event.create("active_redstone")				.thinTexture(0xcc0000).bucketColor(0xcc0000)	.displayName("Molten Active Redstone").noBlock()
	event.create("seed_oil_water")				.thinTexture(0x936e52).bucketColor(0x936e52)	.displayName("Tree Seed Oil Water").noBlock() 
	event.create("resin")						.thinTexture(0xcccc66).bucketColor(0xcccc66)	.displayName("Molten Resin").noBlock() 
	event.create("latex")						.thinTexture(0xcccccc).bucketColor(0xcccccc)	.displayName("Molten latex").noBlock() 
	event.create("birch_sap")					.thinTexture(0x7aabb9).bucketColor(0x7aabb9)	.displayName("Birch Sap").noBlock() 
	event.create("maple_sap")					.thinTexture(0x95b5bf).bucketColor(0x95b5bf)	.displayName("Maple Sap").noBlock() 
	event.create("willow_sap")					.thinTexture(0xa7cbd7).bucketColor(0xa7cbd7)	.displayName("Willow Sap").noBlock() 
	event.create("alcohol")						.thinTexture(0xceeefe).bucketColor(0xceeefe)	.displayName("High-Proof Alcohol").noBlock() 
	event.create("molten_blaze")				.thinTexture(0xffcc66).bucketColor(0xffcc66)	.displayName("Molten Blaze").noBlock()
	event.create("solution_aspergillus_oryzae")	.thinTexture(0xcccccc).bucketColor(0xcccccc)	.displayName("Solution Aspergillus Oryzae").noBlock() 
	event.create("wort")						.thinTexture(0xba8c2f).bucketColor(0xba8c2f)	.displayName("Beer Wort").noBlock()
	event.create("double_wort")					.thinTexture(0xc69564).bucketColor(0xc69564)	.displayName("Double Wort").noBlock()
	event.create("strong_wort")					.thinTexture(0xc69564).bucketColor(0xc69564)	.displayName("Strong Wort").noBlock()
	event.create("clear_wort")					.thinTexture(0xcb9f46).bucketColor(0xcb9f46)	.displayName("Clear Beer Wort").noBlock()
	event.create("bread_beer")					.thinTexture(0x996633).bucketColor(0x996633)	.displayName("Bread Beer").noBlock()
	event.create("green_beer")					.thinTexture(0xb0cd9a).bucketColor(0xb0cd9a)	.displayName("Green Beer").noBlock()
	event.create("young_whiskey")				.thinTexture(0xb9a473).bucketColor(0xb9a473)	.displayName("Young Whiskey").noBlock()
	event.create("young_corn_whiskey")			.thinTexture(0x9c9382).bucketColor(0x9c9382)	.displayName("Young Corn Whiskey").noBlock()
	event.create("young_rye_whiskey")			.thinTexture(0x9d663a).bucketColor(0x9d663a)	.displayName("Young Rye Whiskey").noBlock()
	event.create("whiskey_distillated")			.thinTexture(0xb0cd9a).bucketColor(0xb0cd9a)	.displayName("Whiskey distillated 96%").noBlock()
	event.create("nigori")						.thinTexture(0xf1e5c5).bucketColor(0xf1e5c5)	.displayName("Sake Nigori").noBlock()
	event.create("vodka_mash")					.thinTexture(0xd9cc81).bucketColor(0xd9cc81)	.displayName("Vodka Mash").noBlock()
	event.create("rum_mash")					.thinTexture(0x903232).bucketColor(0x903232)	.displayName("Rum Mash").noBlock()
	event.create("rum_distillated")				.thinTexture(0xb03a56).bucketColor(0xb03a56)	.displayName("Rum distillated 40%").noBlock()
	event.create("slurry_sulfuric_acid_fluorite").thinTexture(0xb03a56).bucketColor(0xb03a56)	.displayName("Fluorite Sulfate").noBlock()
})